### ISSUE TITLE
Animated texture on e1m1 screen has incorrect dimension and alignment

### ISSUE THREAD

**Issue by Calinou** [MissLavender-LQ/LibreQuake#104]
**LibreQuake version:** 0.06-beta

On e1m1, there are animated terminal textures near the end teleporter. Flip back and forth between the two animation frames, notice how the texture doesn't fit the screen and gets misaligned over time:

![e1m1_2024-02-15_20-23-59 webp](https://github.com/MissLavender-LQ/LibreQuake/assets/180032/7c516bd6-1e05-4fd5-aa02-9fcf80e79b3f)

![e1m1_2024-02-15_20-24-00 webp](https://github.com/MissLavender-LQ/LibreQuake/assets/180032/c07f6595-a01f-436f-8c89-ba7463885d72)

I'm using Ironwail 0.7.0 for reference.

**Comment by MissLavender-LQ** [comment]
ya has been fixed

**Comment by MissLavender-LQ** [comment]
could of def been more clear with this commit 
https://github.com/MissLavender-LQ/LibreQuake/commit/1b2ddd1e63122c574e00c32f7b2b733e2f94fa5e
