### ISSUE TITLE
Quake map sources are GPL v2

### ISSUE THREAD

**Issue by jacobo-mc** [MissLavender-LQ/LibreQuake#23]
Why are you remapping? You can just replace models, sounds and textures, as the quakec and maps are free.
https://github.com/id-Software/Quake-Tools/tree/master/qcc/v101qc
https://github.com/fzwoch/quake_map_source

**Comment by MissLav** [comment]
the map sources are **NOT** gpl2 John R was just nice and gave them out 
he did not have permission to do so but he did 
if u look at his  original blog post that he gave out the maps  it **does not** say anything about gpl or them being under a free software license

sorry if this sounds rude i just really dont like that people keep pushing this miss information

**Comment by MissLav** [comment]
https://rome.ro/news/2016/2/14/quake-map-sources-released
https://web.archive.org/web/20061022171208/http://rome.ro/2006/10/quake-map-sources-released.html

**Comment by hogsy** [comment]
Actually if you'd downloaded the map sources from the 2006 upload there, it would've included the GPL license. From what I understand the link to download was broken on Romero's blog after he updated it, and when he uploaded it again he uploaded an earlier copy which lacked the GPL license amendment.

Anyway, here's the copy of it with the GPL license (which is also mentioned in the readme for this copy).

[quake_map_sources.zip](https://github.com/MissLav/LibreQuake/files/8087543/quake_map_sources.zip)

**Comment by jacobo-mc** [comment]
People have been using the maps under GPL for many years, and Mr. Romero did not stop anybody. It is complete misinformation, you saying it is not gpl. The file linked above have timestamps that make sense for the release date.

**Comment by mmillar-bolis** [comment]
So Romero declared his copies of the map source to be GPL some 10 years *after* leaving ID. Are there any statements from ID that support this action?

Because I could just grab some of the software I've written for work and declare it GPL as well -but my slapping a text document in a zip doesn't just make it covered if my company disagrees and can produce evidence to the contrary.

Let me restate that: the best reason to be skeptical of the GPL'd nature of these map sources is that they were never released by ID themselves.

Does anyone have actual, critical proof that ID software, under it's current leadership, sanctions these former-employee map releases as GPL?

**Comment by mmillar-bolis** [comment]
I'm unable to edit on mobile for some reason today, but my point is that maybe we should just ask ID and Romero to double-check permission.

**Comment by hogsy** [comment]
> > There is one reason to avoid using the GPL'd map sources: [LibreQuake is licensed under BSD 3-Clause](https://github.com/MissLav/LibreQuake/blob/master/COPYING).
> > 
> > If LibreQuake aims to keep all of its resources under BSD 3-Clause, then GPL'd resources cannot be used.
> 
> 
> there  is a way to get around that we wouldn't be able to include the gpl stuff in the repo but we could include it in the release with a gpl notice about the said files 
> 
> 
> 
> > Actually if you'd downloaded the map sources from the 2006 archive blog post there (which unfortunately is broken), it would've included the GPL license with the maps. From what I understand the link to download was broken on Romero's blog after he updated it, and when he uploaded it again he uploaded an earlier copy which lacked the GPL license amendment.
> > 
> > Anyway, here's the copy of it with the GPL license (which is also mentioned in the readme for this copy).
> > 
> > [quake_map_sources.zip](https://github.com/MissLav/LibreQuake/files/8087543/quake_map_sources.zip)
> 
> like @mmillar-bolis i am slightly doubtful that he got permission to put them under gpl 
> 
> on top of that its nice to have our own stuff either way if we find out that we can use it we would just include a different download link that has the maps with out bsd3 textures 

That's fair enough! To be honest I just thought I'd point it out but I think the direction you're taking is fine as it is 👍

**Comment by MissLav** [comment]
thank you and yeah its fine to be pointed out i was just operating with the info i had and nothing i saw made it clear that there was a version with the gpl licence inside ill see if i can contact john r on twitter and see what he has to say about it

**Comment by jacobo-mc** [comment]
You can also use the Quake Revitalisation Project to provide placeholder textures.

**Comment by MissLav** [comment]
i was going to do that at one point **but** there are textures in there that are just 100% quake textures upscaled and then a new noise applied on top so that hole pack is likely some what tainted

**Comment by jacobo-mc** [comment]
How about OpenQuartz, whitch is 100% GPL.

**Comment by MissLav** [comment]
we were off with openquartz but didnt like most of the art and that it was all gpl
hell the project was originally going to be called librequartz
![image](https://user-images.githubusercontent.com/51702517/154551200-6aa4acef-8f0a-4b34-bbeb-d8d79c270b8f.png)

**Comment by jacobo-mc** [comment]
You actually can use GPL and BSD-3 stuff together, as they are compatible. Why do you not have a GPL pak and a BSD pak?

**Comment by jacobrogers256** [comment]
Can the Romero Dump be used?
