### ISSUE TITLE
Best qwprogs.dat to use with this?

### ISSUE THREAD

**Issue by poVoq** [MissLavender-LQ/LibreQuake#27]
I tried running the current master branch without any non-Free components in FTEQW and it works reasonably well, however it complains about missing game code.

Placing https://github.com/id-Software/Quake/blob/master/qw-qc/qwprogs.dat into /lq1 works, but I am wondering if there is some recommended improved game-code to use with this (preferrably precompiled for FTEQW)?

I guess one of the qc-clean repos would be a starting point? Like:
https://github.com/maikmerten/LibreProgsDeluxe or https://github.com/shpuld/id1-quakec-cleaned

Edit: the older releases here do seem to include some progs.dat though?

**Comment by poVoq** [comment]
Or maybe this one? https://github.com/Jason2Brownlee/CleanFixedQuakeC/releases/tag/v1.5

(seems to work fine with LibreQuake and FTEQW)

**Comment by MissLavender-LQ** [comment]
i mean we use LibreProgsDeluxe its maintained by one of our team memebers https://github.com/MissLavender-LQ/LibreProgsDeluxe/tree/main 
i have a fork thats just swsynced with maikmerten's

**Comment by MotoLegacy** [comment]
Can this be closed now that QC is built and distributed? @MissLavender-LQ

**Comment by MissLavender-LQ** [comment]
oh i dont remember this
yeah should be closed
