### ISSUE TITLE
Items/Weapons do not lower on lqdm6_b1

### ISSUE THREAD

**Issue by kwadroke** [MissLavender-LQ/LibreQuake#45]
When platforms lower, the items  stay on the Beta 1 version. Previously they came down with the platform.
lqdm6_a7 worked fine.

Tested on FTEQW

Broken by commit: b1c5610

**Comment by kwadroke** [comment]
The map is now called lqdm6 (minus _a# or _b#)

**Comment by MissLavender-LQ** [comment]
@Zungrysoft

**Comment by Zungrysoft** [comment]
Fixed. Thank you for your report!

**Comment by kwadroke** [comment]
Items are lowering as expected now. Thanks!

Love the new look for the map by the way.
