### ISSUE TITLE
Host_Error: Program error

### ISSUE THREAD

**Issue by catfoolyou** [MissLavender-LQ/LibreQuake#95]
This it the error it throws when I try to use pak0 and pak1 instead of the paid version, or when I sideload them with the actual game as pak2 and pak3.

**Comment by MissLavender-LQ** [comment]
what pak2? pak3? this is for quake
and i dont just run the pak u run the id1 dirrectory

**Comment by MissLavender-LQ** [comment]
oh i think i miss understood what u wrote

**Comment by MissLavender-LQ** [comment]
make sure you are grabbing ur game from the releases 
https://github.com/MissLavender-LQ/LibreQuake/releases/tag/v0.05-beta

**Comment by MissLavender-LQ** [comment]
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/2e19b571-ee4f-47bd-9211-6ddf9f15f37c

just to avoid any misunderstanding 
here is a video on how it should work

**Comment by catfoolyou** [comment]
That's a conventional source port. I'm trying to run it with a WASM browser port, which may be the reason it doesn't work. 
Here's the full repo: https://github.com/catfoolyou/LibreQuake-WASM

**Comment by MotoLegacy** [comment]
The mod working in a standard source port and not a modified one is an indication that the engine is bugged. This is very vanilla QuakeC powering the mod, just compiled with FTEQCC. File a report to the engine maintainer instead.

**Comment by catfoolyou** [comment]
Alr, will try that instead.
